### ISSUE TITLE
Cropping Issue

### ISSUE THREAD

**Issue by Greenpoison** [quantumsheep/simplemmo-inventory-market#1]
Upon loading the script, the "use button" is removed from the inventory menu and the sell button does not full appear.
![image](https://user-images.githubusercontent.com/12008125/130822390-e57caf6b-22a5-4fc8-9a62-79d1fb699444.png)

**Comment by Greenpoison** [comment]
Quick update for additional info: Resoution 1920x1080 running Via Chrome Browser windows 10.

**Comment by quantumsheep** [comment]
You should be able to access other buttons by scrolling horizontally (using a touchpad or <kbd>Shift</kbd> + Mouse Wheel).

I don't see much things we can do without changing the CSS of the table or the whole page.

**Comment by Greenpoison** [comment]
Thanks!
